/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasitap;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;



/**
 *
 * @author root
 */
public class data_pembelian extends javax.swing.JInternalFrame {

    private JTable table = null;
    private Connection con = null;
    SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
    private String laporanPembelian;
    Map<String, Object> param = new HashMap<String, Object>();

    /**
     * Creates new form bahan
     */
    public data_pembelian() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((dim.width / 2) - (getSize().width / 2), (dim.height / 2) - (getSize().height / 2));
        tampilTabel();
        tanggal();
        update.setEnabled(false);
        table.setEnabled(false);
    }

    //untuk menampilkan tanggal sesuai sistem
    void tanggal() {
        Date tanggal = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd MMMM yyyy");
        jLabel1.setText(sdf.format(tanggal));
    }

    //untuk mengkoneksikan ke database
    void konek() {
        try {
            String driver = "com.mysql.jdbc.Driver";
            String url = "jdbc:mysql://localhost/db_ayam"; // sesuaikan dengan nama database anda
            String user = "root"; // user mysql anda
            String pass = ""; // passowrd mysql
            con = DriverManager.getConnection(url, user, pass);
            System.err.println("Sukses Koneksi");
        } catch (SQLException ex) {
            System.err.println("Tidak Berhasil Koneksi");
            System.exit(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        id = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tampil = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_modal = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_jumAnkAym = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_harAnkAym = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        totAnkAym = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_jumPkn = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_jumAir = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_jumLstrk = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_jumVksn = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txt_hrgaPkn = new javax.swing.JTextField();
        txt_hrgAir = new javax.swing.JTextField();
        txt_hrgLstrk = new javax.swing.JTextField();
        txt_hrgVksn = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        totVaksin = new javax.swing.JLabel();
        totLstrk = new javax.swing.JLabel();
        totAir = new javax.swing.JLabel();
        totPkn = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        hargaTotal = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        cek = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        kembali1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel11.setText("*Cari data, berdasarkan id");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabel Transaksi Pembelian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tampil)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tampil, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form Transaksi Pembelian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel2.setText("Modal");

        jLabel24.setText("Rp");

        jLabel5.setText("Anak Ayam");

        jLabel3.setText("Jumlah");

        jLabel17.setText("Rp");

        txt_harAnkAym.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_harAnkAymKeyReleased(evt);
            }
        });

        jLabel20.setText("Rp");

        totAnkAym.setText("0");

        jLabel15.setText("Total Harga");

        jLabel6.setText("Pakan");

        jLabel29.setText("Kg");

        jLabel7.setText("Air");

        jLabel8.setText("Listrik");

        jLabel9.setText("Vaksin/Vitamin");

        jLabel25.setText("Rp");

        txt_hrgaPkn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_hrgaPknKeyReleased(evt);
            }
        });

        txt_hrgAir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_hrgAirKeyReleased(evt);
            }
        });

        txt_hrgLstrk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_hrgLstrkKeyReleased(evt);
            }
        });

        txt_hrgVksn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hrgVksnActionPerformed(evt);
            }
        });
        txt_hrgVksn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_hrgVksnKeyReleased(evt);
            }
        });

        jLabel19.setText("Rp");

        jLabel23.setText("Rp");

        jLabel22.setText("Rp");

        jLabel26.setText("Rp");

        jLabel21.setText("Rp");

        jLabel27.setText("Rp");

        jLabel28.setText("Rp");

        totVaksin.setText("0");

        totLstrk.setText("0");

        totAir.setText("0");

        totPkn.setText("0");

        jLabel30.setText("Ekor");

        jLabel31.setText("Lt");

        jLabel32.setText("Watt");

        jLabel33.setText("Kg");

        jLabel10.setText("Jumlah Total Pembelian");

        jLabel34.setText("Rp");

        hargaTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hargaTotal.setForeground(new java.awt.Color(255, 0, 0));
        hargaTotal.setText("0");

        jLabel13.setText("Tanggal Pembelian");

        cek.setText("Total");
        cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekActionPerformed(evt);
            }
        });

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        update.setText("Perbarui");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 0, 0));
        jLabel35.setText("*Pastikan semua data terisi dengan benar !");

        jLabel16.setText("Harga per-satuan");

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt_jumLstrk, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_jumAir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_jumVksn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel31)
                                            .addComponent(jLabel32)
                                            .addComponent(jLabel33)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(128, 128, 128)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txt_harAnkAym, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel16))
                                            .addGap(46, 46, 46))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txt_jumAnkAym, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txt_jumPkn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel29)
                                                .addComponent(jLabel30))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel17)
                                            .addGap(140, 140, 140))
                                        .addComponent(jLabel10)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel22)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txt_hrgVksn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel23)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txt_hrgLstrk, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel19)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txt_hrgAir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel25)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txt_hrgaPkn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(46, 46, 46))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(totAnkAym)
                                            .addComponent(totPkn)
                                            .addComponent(totVaksin)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel34)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hargaTotal))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(totLstrk))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(totAir))))
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(48, 48, 48)
                        .addComponent(cek))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186)
                        .addComponent(simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(update)))
                .addGap(281, 281, 281))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel1))
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_modal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_jumAnkAym, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txt_harAnkAym, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(totAnkAym)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_hrgaPkn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(totPkn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_hrgAir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21)
                            .addComponent(totAir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_hrgLstrk, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_hrgVksn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel28)
                            .addComponent(totVaksin)
                            .addComponent(cek, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34)
                            .addComponent(hargaTotal)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_jumPkn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_jumAir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel31)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_jumLstrk, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel32)
                            .addComponent(totLstrk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_jumVksn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(136, 136, 136))
        );

        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        kembali1.setText("Cetak");
        kembali1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembali1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(kembali1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kembali1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        //untuk tombol simpan
        try {
            konek();
            PreparedStatement pStatement = null;
            String sql = "insert into pembellian"
                    + "(modal,"
                    + "jumAnkAym,"
                    + "hrgAnkAym,"
                    + "jumPkn,"
                    + "hrgPkn,"
                    + "jumAir,"
                    + "hrgAir,"
                    + "jumListrik,"
                    + "hrgListrik,"
                    + "jumVaksin,"
                    + "hrgVaksin,"
                    + "hrgTotal,"
                    + "tgl)"
                    + "Values (?,?,?,?,?,?,?,?,?,?,?,?,?)";
            pStatement = con.prepareStatement(sql);
            pStatement.setString(1, txt_modal.getText());
            pStatement.setString(2, txt_jumAnkAym.getText());
            pStatement.setString(3, txt_harAnkAym.getText());
            pStatement.setString(4, txt_jumPkn.getText());
            pStatement.setString(5, txt_hrgaPkn.getText());
            pStatement.setString(6, txt_jumAir.getText());
            pStatement.setString(7, txt_hrgAir.getText());
            pStatement.setString(8, txt_jumLstrk.getText());
            pStatement.setString(9, txt_hrgLstrk.getText());
            pStatement.setString(10, txt_jumVksn.getText());
            pStatement.setString(11, txt_hrgVksn.getText());
            pStatement.setString(12, hargaTotal.getText());
            pStatement.setString(13, jLabel1.getText());
            int intTambah = pStatement.executeUpdate();
            if (intTambah > 0) {
                JOptionPane.showMessageDialog(this, "Transaksi Sukses", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Transaksi Gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
            pStatement.close();
            id.setText(null);
            txt_modal.setText("");
            txt_jumAnkAym.setText("");
            txt_harAnkAym.setText("");
            txt_jumPkn.setText("");
            txt_hrgaPkn.setText("");
            txt_jumAir.setText("");
            txt_hrgAir.setText("");
            txt_jumLstrk.setText("");
            txt_hrgLstrk.setText("");
            txt_jumVksn.setText("");
            txt_hrgVksn.setText("");
            hargaTotal.setText("0");
            //txt_tgl.setDateFormatString("");
            totAir.setText("0");
            totAnkAym.setText("0");
            totLstrk.setText("0");
            totPkn.setText("0");
            totVaksin.setText("0");
            tanggal();
            tampilTabel();
        } catch (SQLException e) {
            System.out.println("Koneksi Gagal" + e.toString());
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        this.dispose(); //untuk tombol kembali
    }//GEN-LAST:event_kembaliActionPerformed

    private void cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekActionPerformed
        //untuk tombol total
        long jum6;
        int totay = Integer.valueOf(totAnkAym.getText());
        int totp = Integer.valueOf(totPkn.getText());
        int tota = Integer.valueOf(totAir.getText());
        int totl = Integer.valueOf(totLstrk.getText());
        int totv = Integer.valueOf(totVaksin.getText());
        jum6 = (totay + totp + tota + totl + totv);
        hargaTotal.setText("" + jum6 + "");
    }//GEN-LAST:event_cekActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
       //untuk tombol cari
        try {
            update.setEnabled(true);
            simpan.setEnabled(false);
            konek();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select * from pembellian Where id='" + id.getText() + "'");
            if (rs.next()) {
                //bSimpan.setEnabled(false);
                txt_modal.setText(rs.getString("modal"));
                jLabel1.setText(rs.getString("tgl"));
                txt_jumAnkAym.setText(rs.getString("jumAnkAym"));
                txt_harAnkAym.setText(rs.getString("hrgAnkAym"));
                txt_jumPkn.setText(rs.getString("jumPkn"));
                txt_hrgaPkn.setText(rs.getString("hrgPkn"));
                txt_jumAir.setText(rs.getString("jumAir"));
                txt_hrgAir.setText(rs.getString("hrgAir"));
                txt_jumLstrk.setText(rs.getString("jumListrik"));
                txt_hrgLstrk.setText(rs.getString("hrgListrik"));
                txt_jumVksn.setText(rs.getString("jumVaksin"));
                txt_hrgVksn.setText(rs.getString("hrgVaksin"));
            } else {
                JOptionPane.showMessageDialog(this, "Tanggal belum terisi, Silahkan isi Tanggal terlebih dahulu !!!", "Information", JOptionPane.INFORMATION_MESSAGE);
                txt_modal.setText("");
                txt_jumAnkAym.setText("");
                txt_harAnkAym.setText("");
                txt_jumPkn.setText("");
                txt_hrgaPkn.setText("");
                txt_jumAir.setText("");
                txt_hrgAir.setText("");
                txt_jumLstrk.setText("");
                txt_hrgLstrk.setText("");
                txt_jumVksn.setText("");
                txt_hrgVksn.setText("");
            }
        } catch (SQLException e) {
            System.out.println("Koneksi Gagal" + e.toString());
        }
    }//GEN-LAST:event_cariActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        //untuk tombol perbarui
        try {
            update.setEnabled(false);
            simpan.setEnabled(true);
            konek();
            PreparedStatement pStatement = null;
            String sql = "update pembellian set modal=?,jumAnkAym=?,hrgAnkAym=?,jumPkn=?,hrgPkn=?,jumAir=?,hrgAir=?,jumListrik=?,hrgListrik=?,jumVaksin=?,hrgVaksin=?,hrgTotal=?, tgl=? where id=?";
            pStatement = con.prepareStatement(sql);
            pStatement.setString(14, id.getText());
            pStatement.setString(1, txt_modal.getText());
            pStatement.setString(2, txt_jumAnkAym.getText());
            pStatement.setString(3, txt_harAnkAym.getText());
            pStatement.setString(4, txt_jumPkn.getText());
            pStatement.setString(5, txt_hrgaPkn.getText());
            pStatement.setString(6, txt_jumAir.getText());
            pStatement.setString(7, txt_hrgAir.getText());
            pStatement.setString(8, txt_jumLstrk.getText());
            pStatement.setString(9, txt_hrgLstrk.getText());
            pStatement.setString(10, txt_jumVksn.getText());
            pStatement.setString(11, txt_hrgVksn.getText());
            pStatement.setString(12, hargaTotal.getText());
            pStatement.setString(13, jLabel1.getText());
            int intTambah = pStatement.executeUpdate();
            if (intTambah > 0) {
                JOptionPane.showMessageDialog(this, "Edit Sukses", "Information", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Edit Gagal", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
            pStatement.close();
            //bSimpan.setEnabled(true);
            //bEdit.setEnabled(false);
            //bHapus.setEnabled(true);
            id.setText(null);
            txt_modal.setText("");
            txt_jumAnkAym.setText("");
            txt_harAnkAym.setText("");
            txt_jumPkn.setText("");
            txt_hrgaPkn.setText("");
            txt_jumAir.setText("");
            txt_hrgAir.setText("");
            txt_jumLstrk.setText("");
            txt_hrgLstrk.setText("");
            txt_jumVksn.setText("");
            txt_hrgVksn.setText("");
            hargaTotal.setText("0");
            tanggal();
            totAir.setText("0");
            totAnkAym.setText("0");
            totLstrk.setText("0");
            totPkn.setText("0");
            totVaksin.setText("0");
            tampilTabel();
        } catch (SQLException e) {
            System.out.println("Koneksi Gagal" + e.toString());
        }
    }//GEN-LAST:event_updateActionPerformed

    private void txt_harAnkAymKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_harAnkAymKeyReleased
        //agar saat jumlah dan harga anak ayam telah diisi otomatis mentotal
        long jum1;
        int jAym = Integer.valueOf(txt_jumAnkAym.getText());
        int hAym = Integer.valueOf(txt_harAnkAym.getText());
        jum1 = (jAym * hAym);
        totAnkAym.setText("" + jum1 + "");

    }//GEN-LAST:event_txt_harAnkAymKeyReleased

    private void txt_hrgaPknKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hrgaPknKeyReleased
        //agar saat jumlah dan harga pakan telah diisi otomatis mentotal
        long jum2;
        int jPkn = Integer.valueOf(txt_jumPkn.getText());
        int hPkn = Integer.valueOf(txt_hrgaPkn.getText());
        jum2 = (jPkn * hPkn);
        totPkn.setText("" + jum2 + "");
    }//GEN-LAST:event_txt_hrgaPknKeyReleased

    private void txt_hrgAirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hrgAirKeyReleased
        //agar saat jumlah dan harga air telah diisi otomatis mentotal
        long jum3;
        int jAir = Integer.valueOf(txt_jumAir.getText());
        int hAir = Integer.valueOf(txt_hrgAir.getText());
        jum3 = (jAir * hAir);
        totAir.setText("" + jum3 + "");
    }//GEN-LAST:event_txt_hrgAirKeyReleased

    private void txt_hrgLstrkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hrgLstrkKeyReleased
        //agar saat jumlah dan harga listrik telah diisi otomatis mentotal
        long jum4;
        int jListrik = Integer.valueOf(txt_jumLstrk.getText());
        int hListrik = Integer.valueOf(txt_hrgLstrk.getText());
        jum4 = (jListrik * hListrik);
        totLstrk.setText("" + jum4 + "");
    }//GEN-LAST:event_txt_hrgLstrkKeyReleased

    private void txt_hrgVksnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hrgVksnKeyReleased
        //agar saat jumlah dan harga Vaksin telah diisi otomatis mentotal
        long jum5;
        int jVaksin = Integer.valueOf(txt_jumVksn.getText());
        int hVaksin = Integer.valueOf(txt_hrgVksn.getText());
        jum5 = (jVaksin * hVaksin);
        totVaksin.setText("" + jum5 + "");
    }//GEN-LAST:event_txt_hrgVksnKeyReleased

    private void txt_hrgVksnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hrgVksnActionPerformed
        //agar saat total semua telah terisi telah terisi menekan enter total harga akan muncul
        long jum6;
        int totay = Integer.valueOf(totAnkAym.getText());
        int totp = Integer.valueOf(totPkn.getText());
        int tota = Integer.valueOf(totAir.getText());
        int totl = Integer.valueOf(totLstrk.getText());
        int totv = Integer.valueOf(totVaksin.getText());

        jum6 = (totay + totp + tota + totl + totv);
        hargaTotal.setText("" + jum6 + "");
    }//GEN-LAST:event_txt_hrgVksnActionPerformed

    private void kembali1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembali1ActionPerformed
        //untuk tombol cetak
        try {
            table.print();
        } catch (PrinterException e) {
        }
    }//GEN-LAST:event_kembali1ActionPerformed

    //mengambil data daridatabase
    private Object[][] getData() {
        Object[][] data1 = null;
        try {
            konek();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select * from pembellian");
            rs.last();
            int rowCount = rs.getRow();
            rs.beforeFirst();
            data1 = new Object[rowCount][13];
            int no = -1;
            while (rs.next()) {
                no = no + 1;
                data1[no][0] = rs.getString("id");
                data1[no][1] = rs.getString("modal");
                data1[no][2] = rs.getString("hrgAnkAym");
                data1[no][3] = rs.getString("jumAnkAym");
                data1[no][4] = rs.getString("hrgPkn");
                data1[no][5] = rs.getString("jumPkn");
                data1[no][6] = rs.getString("hrgAir");
                data1[no][7] = rs.getString("jumAir");
                data1[no][8] = rs.getString("hrgListrik");
                data1[no][9] = rs.getString("jumListrik");
                data1[no][10] = rs.getString("hrgVaksin");
                data1[no][11] = rs.getString("jumVaksin");
                data1[no][12] = rs.getString("tgl");
            }
            st.close();

        } catch (SQLException e) {
            System.out.println("Sorry, Koneksi GAGAL");
        }
        return data1;
    }

    //menampilkannya di tabel
    private void tampilTabel() {
        String[] columnNames = {"ID", "Modal", " Harga Anak Ayam", "Jumlah", "Harga Pakan", "Jumlah", "Harga Air", "Jumlah", "Harga Listrik", "Jumlah", "Harga Vaksin", "Jumlah", "Tanggal"};
        table = new JTable(getData(), columnNames);
        tampil.setViewportView(table);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_pembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari;
    private javax.swing.JButton cek;
    private javax.swing.JLabel hargaTotal;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton kembali;
    private javax.swing.JButton kembali1;
    private javax.swing.JButton simpan;
    private javax.swing.JScrollPane tampil;
    private javax.swing.JLabel totAir;
    private javax.swing.JLabel totAnkAym;
    private javax.swing.JLabel totLstrk;
    private javax.swing.JLabel totPkn;
    private javax.swing.JLabel totVaksin;
    private javax.swing.JTextField txt_harAnkAym;
    private javax.swing.JTextField txt_hrgAir;
    private javax.swing.JTextField txt_hrgLstrk;
    private javax.swing.JTextField txt_hrgVksn;
    private javax.swing.JTextField txt_hrgaPkn;
    private javax.swing.JTextField txt_jumAir;
    private javax.swing.JTextField txt_jumAnkAym;
    private javax.swing.JTextField txt_jumLstrk;
    private javax.swing.JTextField txt_jumPkn;
    private javax.swing.JTextField txt_jumVksn;
    private javax.swing.JTextField txt_modal;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
