package aplikasitap;
import java.sql.*;
import javax.swing.*;
public class home extends javax.swing.JFrame {
    Connection con;
    
    public home() {
        setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        jmasuk.setVisible(false);
        menu_keluar.setEnabled(false);
        menu_data.setEnabled(false);
        menu_trans.setEnabled(false);
    }

    // untuk mengkoneksikan ke database
    void konek() { 
        try {
            String driver = "com.mysql.jdbc.Driver";
            String url = "jdbc:mysql://localhost/db_ayam"; // sesuaikan dengan nama database anda
            String user = "root"; // user mysql anda
            String pass = ""; // passowrd mysql
            con = DriverManager.getConnection(url, user, pass);
            System.err.println("Sukses Koneksi");
        } catch (SQLException ex) {
            System.err.println("Tidak Berhasil Koneksi");
            System.exit(1);
        }
    }
    
    // untuk menampilkan form pembelian
    private void tampilBeli() {
        data_pembelian beli = new data_pembelian();
        panelbg_home1.add(beli);
        beli.setVisible(true);
    }

    // untuk menampilkan form penjualan
    private void tampilJual() {
        data_penjualan jual = new data_penjualan();
        panelbg_home1.add(jual);
        jual.setVisible(true);
    }

    // untuk menampilkan form data ayam
    private void tampilAyam() {
        dataAyam ayam = new dataAyam();
        panelbg_home1.add(ayam);
        ayam.setVisible(true);
    }

    // untuk menampilkan form data telur
    private void tampilTelur() {
        dataTelur telur = new dataTelur();
        panelbg_home1.add(telur);
        telur.setVisible(true);
    }

    // untuk menampilkan form data kotoran
    private void tampilKotoran() {
        dataKotoran kotor = new dataKotoran();
        panelbg_home1.add(kotor);
        kotor.setVisible(true);
    }

    // untuk menampilkan form pembuat program
    private void tampilBuat() {
        about buat = new about();
        panelbg_home1.add(buat);
        buat.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelbg_login1 = new panelbg.panelbg_login();
        panelbg_home1 = new panelbg.panelbg_home();
        jmasuk = new javax.swing.JPanel();
        panelbg_login2 = new panelbg.panelbg_login();
        jlogin = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        txt_nama = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_masuk = new javax.swing.JMenuItem();
        menu_keluar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        keluar_prog = new javax.swing.JMenuItem();
        menu_trans = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        menu_data = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout panelbg_login1Layout = new javax.swing.GroupLayout(panelbg_login1);
        panelbg_login1.setLayout(panelbg_login1Layout);
        panelbg_login1Layout.setHorizontalGroup(
            panelbg_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelbg_login1Layout.setVerticalGroup(
            panelbg_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Ternak Ayam Petelur - V.Beta");

        jmasuk.setLayout(new java.awt.BorderLayout());

        jlogin.setText("Masuk");
        jlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloginActionPerformed(evt);
            }
        });

        jButton2.setText("Batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Meiryo UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Meiryo UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kata Sandi");

        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });

        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelbg_login2Layout = new javax.swing.GroupLayout(panelbg_login2);
        panelbg_login2.setLayout(panelbg_login2Layout);
        panelbg_login2Layout.setHorizontalGroup(
            panelbg_login2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbg_login2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelbg_login2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(panelbg_login2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelbg_login2Layout.createSequentialGroup()
                        .addComponent(jlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                    .addComponent(pass)
                    .addComponent(txt_nama))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelbg_login2Layout.setVerticalGroup(
            panelbg_login2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbg_login2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panelbg_login2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelbg_login2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelbg_login2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlogin)
                    .addComponent(jButton2))
                .addContainerGap(269, Short.MAX_VALUE))
        );

        jmasuk.add(panelbg_login2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panelbg_home1Layout = new javax.swing.GroupLayout(panelbg_home1);
        panelbg_home1.setLayout(panelbg_home1Layout);
        panelbg_home1Layout.setHorizontalGroup(
            panelbg_home1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbg_home1Layout.createSequentialGroup()
                .addComponent(jmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(474, Short.MAX_VALUE))
        );
        panelbg_home1Layout.setVerticalGroup(
            panelbg_home1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jmasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(panelbg_home1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Kunci");

        menu_masuk.setText("Masuk");
        menu_masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_masukActionPerformed(evt);
            }
        });
        jMenu1.add(menu_masuk);

        menu_keluar.setText("Keluar");
        menu_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_keluarActionPerformed(evt);
            }
        });
        jMenu1.add(menu_keluar);
        jMenu1.add(jSeparator1);

        keluar_prog.setText("Keluar Program");
        keluar_prog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluar_progActionPerformed(evt);
            }
        });
        jMenu1.add(keluar_prog);

        jMenuBar1.add(jMenu1);

        menu_trans.setText("Transaksi");

        jMenuItem4.setText("Pembelian");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menu_trans.add(jMenuItem4);

        jMenuItem8.setText("Penjualan");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        menu_trans.add(jMenuItem8);

        jMenuBar1.add(menu_trans);

        menu_data.setText("Data");

        jMenuItem5.setText("Data Ayam");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menu_data.add(jMenuItem5);

        jMenuItem6.setText("Data Telur");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menu_data.add(jMenuItem6);

        jMenuItem7.setText("Data Kotoran");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        menu_data.add(jMenuItem7);

        jMenuBar1.add(menu_data);

        jMenu2.setText("Tentang");

        jMenuItem1.setText("Pembuat");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_masukActionPerformed
        jmasuk.setVisible(true); //ketika menekan tombol menu masuk maka akan otomatis form login tampil
    }//GEN-LAST:event_menu_masukActionPerformed

    private void menu_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_keluarActionPerformed
       //untuk menu keluar login
        int ok = JOptionPane.showConfirmDialog(null, "Apakah anda ingin keluar program ?", "Pertanyaan", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            menu_data.setEnabled(false);
            menu_trans.setEnabled(false);
            menu_keluar.setEnabled(false);
            menu_masuk.setEnabled(true);
            keluar_prog.setEnabled(true);
        } else {

        }
    }//GEN-LAST:event_menu_keluarActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        tampilAyam(); // untuk menampilkan form menu data ayam
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void jloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloginActionPerformed
        // untuk form login tombol masuk
        try {
            konek();
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("select count(nama) from admin where nama='" + txt_nama.getText() + "' and pass='" + pass.getText() + "'");

            if (rs.next()) {
                int nama = rs.getInt(1);
                if (nama > 0) {
                    JOptionPane.showMessageDialog(null, "Login Berhasil", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                    jmasuk.setVisible(false);
                    menu_keluar.setEnabled(true);
                    menu_data.setEnabled(true);
                    menu_masuk.setEnabled(false);
                    menu_trans.setEnabled(true);
                    keluar_prog.setEnabled(false);

                    txt_nama.setText("");
                    pass.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "Nama atau Kata Sandi Salah", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                    txt_nama.setText("");
                    pass.setText("");
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Username dan Password Salah\n" + e);
        }


    }//GEN-LAST:event_jloginActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jmasuk.setVisible(false); // otomatis hilang ketika berhasil login
    }//GEN-LAST:event_jButton2ActionPerformed

    private void keluar_progActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluar_progActionPerformed
        System.exit(1); // keluar program
    }//GEN-LAST:event_keluar_progActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        tampilBeli(); // memanggil method tampilBeli();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        tampilJual(); // memanggil method tampilJual();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        tampilTelur(); // memanggil method tampilTelur();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        tampilKotoran(); // memanggil method tampilKotoran();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        tampilBuat(); // memanggil method tampilBuat();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton jlogin;
    private javax.swing.JPanel jmasuk;
    private javax.swing.JMenuItem keluar_prog;
    private javax.swing.JMenu menu_data;
    private javax.swing.JMenuItem menu_keluar;
    private javax.swing.JMenuItem menu_masuk;
    private javax.swing.JMenu menu_trans;
    private panelbg.panelbg_home panelbg_home1;
    private panelbg.panelbg_login panelbg_login1;
    private panelbg.panelbg_login panelbg_login2;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField txt_nama;
    // End of variables declaration//GEN-END:variables
}
